[tool.black]
line-length = 70  # Make this consistent with your flake8 settings
exclude = '''
/(
    \.git
  | \.venv
  | \.idea
  | pipeline/Data
  | pipeline/Inputs
  | pipeline/Outputs
  | pipeline/Scripts
  | pipeline/Validation
)/
'''
