directories:
  input: "pipeline/Inputs/experiments_data/GSE/XLSX"  # Directory containing input Excel files
  output_base: "pipeline/Outputs/NGSEA"               # Base directory for output results
  summary_base: "pipeline/Outputs/NGSEA/Summary"      # Directory for summary results
  pathways: "pipeline/Data/H_sapiens/pathways"        # Directory containing pathway data

analysis_settings:
  networks:
    - "H_sapiens"                                    # List of networks to analyze
  pathway_files:
    - "kegg"                                 # List of pathway files to process
  prop_methods:                                      # Propagation methods to use
    - "PEANUT"
  alphas:
    - 0.2                                            # Alpha values for analysis
  max_workers: 1                                    # Number of parallel workers
  JAC_THRESHOLD: 0.2                                 # Jaccard index threshold for pathway filtering
  FDR_threshold: 0.05     
logging:
  level: "DEBUG"                                       # Logging level (e.g., DEBUG, INFO, WARNING)
  format: "%(asctime)s - %(levelname)s - %(message)s" # Logging format

  
pre_calculated_data:
  KEGG_ACUTE_MYELOID_LEUKEMIA:
  - KEGG_MAPK_SIGNALING_PATHWAY
  - KEGG_CELL_CYCLE
  - KEGG_MTOR_SIGNALING_PATHWAY
  - KEGG_PI3K_AKT_SIGNALING_PATHWAY
  - KEGG_APOPTOSIS
  - KEGG_JAK_STAT_SIGNALING_PATHWAY
  - KEGG_HEMATOPOIETIC_CELL_LINEAGE
  KEGG_ALZHEIMERS_DISEASE:
  - KEGG_OXIDATIVE_PHOSPHORYLATION
  - KEGG_PROTEASOME
  - KEGG_CALCIUM_SIGNALING_PATHWAY
  - KEGG_APOPTOSIS
  - KEGG_WNT_SIGNALING_PATHWAY
  - KEGG_INSULIN_SIGNALING_PATHWAY
  - KEGG_AGE_RAGE_SIGNALING_PATHWAY
  KEGG_COLORECTAL_CANCER:
  - KEGG_MAPK_SIGNALING_PATHWAY
  - KEGG_ERBB_SIGNALING_PATHWAY
  - KEGG_CELL_CYCLE
  - KEGG_P53_SIGNALING_PATHWAY
  - KEGG_MTOR_SIGNALING_PATHWAY
  - KEGG_PI3K_AKT_SIGNALING_PATHWAY
  - KEGG_APOPTOSIS
  - KEGG_WNT_SIGNALING_PATHWAY
  - KEGG_TGF_BETA_SIGNALING_PATHWAY
  KEGG_DILATED_CARDIOMYOPATHY:
  - KEGG_CARDIAC_MUSCLE_CONTRACTION
  - KEGG_TGF_BETA_SIGNALING_PATHWAY
  - KEGG_ECM_RECEPTOR_INTERACTION
  - KEGG_VIRAL_MYOCARDITIS
  KEGG_GLIOMA:
  - KEGG_MAPK_SIGNALING_PATHWAY
  - KEGG_ERBB_SIGNALING_PATHWAY
  - KEGG_CALCIUM_SIGNALING_PATHWAY
  - KEGG_CYTOKINE_CYTOKINE_RECEPTOR_INTERACTION
  - KEGG_CELL_CYCLE
  - KEGG_P53_SIGNALING_PATHWAY
  - KEGG_MTOR_SIGNALING_PATHWAY
  KEGG_HUNTINGTONS_DISEASE:
  - KEGG_OXIDATIVE_PHOSPHORYLATION
  - KEGG_BASAL_TRANSCRIPTION_FACTORS
  - KEGG_RNA_POLYMERASE
  - KEGG_PROTEASOME
  - KEGG_CALCIUM_SIGNALING_PATHWAY
  - KEGG_P53_SIGNALING_PATHWAY
  - KEGG_ENDOCYTOSIS
  - KEGG_APOPTOSIS
  KEGG_NON_SMALL_CELL_LUNG_CANCER:
  - KEGG_MAPK_SIGNALING_PATHWAY
  - KEGG_ERBB_SIGNALING_PATHWAY
  - KEGG_RAS_SIGNALING_PATHWAY
  - KEGG_CALCIUM_SIGNALING_PATHWAY
  - KEGG_CELL_CYCLE
  - KEGG_P53_SIGNALING_PATHWAY
  - KEGG_PI3K_AKT_SIGNALING_PATHWAY
  KEGG_PANCREATIC_CANCER:
  - KEGG_MAPK_SIGNALING_PATHWAY
  - KEGG_ERBB_SIGNALING_PATHWAY
  - KEGG_P53_SIGNALING_PATHWAY
  - KEGG_CELL_CYCLE
  - KEGG_PI3K_AKT_SIGNALING_PATHWAY
  - KEGG_APOPTOSIS
  - KEGG_TGF_BETA_SIGNALING_PATHWAY
  - KEGG_VEGF_SIGNALING_PATHWAY
  - KEGG_JAK_STAT_SIGNALING_PATHWAY
  KEGG_PARKINSONS_DISEASE:
  - KEGG_OXIDATIVE_PHOSPHORYLATION
  - KEGG_TYROSINE_METABOLISM
  - KEGG_PROTEASOME
  - KEGG_CALCIUM_SIGNALING_PATHWAY
  - KEGG_UBIQUITIN_MEDIATED_PROTEOLYSIS
  - KEGG_APOPTOSIS
  KEGG_PROSTATE_CANCER:
  - KEGG_STEROID_HORMONE_BIOSYNTHESIS
  - KEGG_MAPK_SIGNALING_PATHWAY
  - KEGG_CYTOKINE_CYTOKINE_RECEPTOR_INTERACTION
  - KEGG_CELL_CYCLE
  - KEGG_P53_SIGNALING_PATHWAY
  - KEGG_PI3K_AKT_SIGNALING_PATHWAY
  - KEGG_APOPTOSIS
  KEGG_RENAL_CELL_CARCINOMA:
  - KEGG_CITRATE_CYCLE_TCA_CYCLE
  - KEGG_MAPK_SIGNALING_PATHWAY
  - KEGG_HIF1_SIGNALING_PATHWAY
  - KEGG_UBIQUITIN_MEDIATED_PROTEOLYSIS
  - KEGG_TGF_BETA_SIGNALING_PATHWAY
  - KEGG_VEGF_SIGNALING_PATHWAY
  KEGG_THYROID_CANCER:
  - KEGG_PPAR_SIGNALING_PATHWAY
  - KEGG_MAPK_SIGNALING_PATHWAY
  - KEGG_P53_SIGNALING_PATHWAY
  - KEGG_WNT_SIGNALING_PATHWAY
  - KEGG_ADHERENS_JUNCTION
