directories:
  input: "pipeline/Inputs/experiments_data/GSE/XLSX"  # Directory containing input Excel files
  output_base: "pipeline/Outputs"               # Base directory for output results
  summary_base: "pipeline/Outputs/Summary"      # Directory for summary results
  pathways: "pipeline/Data/H_sapiens/pathways"        # Directory containing pathway data

analysis_settings:
  imputation_modes:
    - "both"        # Genes in both dataset and network
    - "dataset"     # Genes in both + genes only in dataset (original score)
    - "network"     # Genes in both + genes only in network (propagated score)
    - "all"         # All genes (original + propagated scores)

  networks:
    - "Anat"                                    # List of networks to analyze
  pathway_files:
    - "kegg"                                 # List of pathway files to process
  prop_methods:                                      # Propagation methods to use
    - "PEANUT"
 
  alphas:
    - 0.2                                            # Alpha values for analysis
  max_workers: 1                                    # Number of parallel workers
  FDR_threshold: 0.05     
logging:
  level: "DEBUG"                                       # Logging level (e.g., DEBUG, INFO, WARNING)
  format: "%(asctime)s - %(levelname)s - %(message)s" # Logging format
