version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  app_file:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: "pipeline/Outputs/logs/app.log"
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  access_file:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: "pipeline/Outputs/logs/access.log"
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  error_file:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: "pipeline/Outputs/logs/error.log"
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  uvicorn:
    level: INFO
    handlers: [console, app_file]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [console, access_file]
    propagate: no
  uvicorn.error:
    level: ERROR
    handlers: [console, error_file]
    propagate: no
  app:  # Add logger for your application
    level: DEBUG
    handlers: [console, app_file]
    propagate: no
  app.pipeline_runner:
    level: DEBUG
    handlers: [console, app_file]
    propagate: no
  app.routes:
    level: DEBUG
    handlers: [console, app_file]
    propagate: no
  app.temp_manager:
    level: DEBUG
    handlers: [console, app_file]
    propagate: no
  app.utils:
    level: DEBUG
    handlers: [console, app_file]
    propagate: no

root:
  level: INFO
  handlers: [console, app_file]
  propagate: no
