version: 1
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

disable_existing_loggers: true  # Disable handlers from imported libraries

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
    stream: ext://sys.stdout
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    filename: "/app/pipeline/Outputs/logs/app.log"
    maxBytes: 10485760
    backupCount: 5
    level: DEBUG

root:
  level: DEBUG
  handlers: [console, rotating_file]
