version: 1
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  file:
    class: logging.FileHandler
    formatter: standard
    filename: "pipeline/Outputs/logs/app.log"  # Path to store logs in pipeline/Outputs/logs
    level: DEBUG

  rotating_file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    filename: "pipeline/Outputs/logs/app.log"  # Path for rotating logs
    maxBytes: 10485760  # 10MB
    backupCount: 5
    level: DEBUG

root:
  level: DEBUG
  handlers: [file, rotating_file]  # Removed 'console' from handlers