# Pipeline configuration file
experiment_name: 'test_experiment'
species: 'H_sapiens'
alpha: 0.1

# Network configuration
network_type: 'default'  # 'default' or 'custom'
network_name: 'Anat'  # For default: 'Anat' or 'HumanNet', for custom: filename without extension
network_path: 'pipeline/Data/H_sapiens/network/Anat'  # Full path for custom networks

pathway_file: 'kegg'
MIN_GENES_PER_PATHWAY: 15
MAX_GENES_PER_PATHWAY: 500
FDR_THRESHOLD: 0.05
run_gsea: false
restrict_to_network: false
create_similarity_matrix: false
figure_title: 'Pathway Enrichment'

# Test input files
condition_data_files:
  # - 'pipeline/Inputs/experiments_data/GSE/XLSX/GSE5281EC_KEGG_ALZHEIMERS_DISEASE.xlsx'
  # - 'pipeline/Inputs/experiments_data/GSE/XLSX/GSE1297_KEGG_ALZHEIMERS_DISEASE.xlsx'
  - 'pipeline/Inputs/experiments_data/GSE/XLSX/GSE5281VCX_KEGG_ALZHEIMERS_DISEASE.xlsx'